language: java

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - TEST_DIR=python; TEST_SCRIPT="python setup.py test"
  - TEST_DIR=scala;  TEST_SCRIPT="mvn test"
  - TEST_DIR=cpp;    TEST_SCRIPT="make";     CXX="g++-4.8"

script: cd $TEST_DIR;  $TEST_SCRIPT
