language: java

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

env:
  - TEST_DIR=python; TEST_SCRIPT="python setup.py test"
  - TEST_DIR=scala;  TEST_SCRIPT="mvn test"
  - TEST_DIR=cpp;    TEST_SCRIPT="alias g++=g++-4.8;  make"

script: cd $TEST_DIR;  $TEST_SCRIPT;  cd ..
