language: java

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
  - sudo apt-get install g++-4.8  &&  alias g++=g++-4.8

env:
  - TEST_DIR=python; TEST_SCRIPT="python setup.py test"
  - TEST_DIR=scala;  TEST_SCRIPT="mvn test"
  - TEST_DIR=cpp;    TEST_SCRIPT="make"

script: cd $TEST_DIR  &&  $TEST_SCRIPT  &&  cd ..
